// migrate_cmd.go — `wowapi migrate` helpers (Phase 10). `create` scaffolds the
// next-numbered goose migration file; the actual apply lives in the product's
// cmd/migrate (generated by `wowapi init`) which calls database.Migrate.
package cli

import (
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
)

var (
	migNameRE = regexp.MustCompile(`^[a-z][a-z0-9_]*$`)
	migFileRE = regexp.MustCompile(`^(\d{5})_.*\.sql$`)
)

func migrateUsage(w io.Writer) {
	fmt.Fprint(w, `usage: wowapi migrate <subcommand> [flags]

Subcommands:
  create   scaffold the next-numbered goose migration file

Flags (create):
  --dir    migrations directory (default "migrations")
  --name   migration name, snake_case (required)
`)
}

func runMigrate(args []string, stdout, stderr io.Writer) int {
	if len(args) == 0 {
		migrateUsage(stderr)
		return 2
	}
	switch args[0] {
	case "create":
		return runMigrateCreate(args[1:], stdout, stderr)
	case "-h", "--help", "help":
		migrateUsage(stdout)
		return 0
	default:
		fmt.Fprintf(stderr, "wowapi migrate: unknown subcommand %q\n", args[0])
		migrateUsage(stderr)
		return 2
	}
}

func runMigrateCreate(args []string, stdout, stderr io.Writer) int {
	fs := flag.NewFlagSet("wowapi migrate create", flag.ContinueOnError)
	fs.SetOutput(stderr)
	dir := fs.String("dir", "migrations", "migrations directory")
	name := fs.String("name", "", "migration name, snake_case")
	if err := fs.Parse(args); err != nil {
		return 2
	}
	if *name == "" {
		fmt.Fprintln(stderr, "wowapi migrate create: --name is required")
		return 2
	}
	if !migNameRE.MatchString(*name) {
		fmt.Fprintln(stderr, "wowapi migrate create: --name must be snake_case ([a-z][a-z0-9_]*)")
		return 1
	}
	next, err := nextMigrationNumber(*dir)
	if err != nil {
		fmt.Fprintf(stderr, "wowapi migrate create: %v\n", err)
		return 1
	}
	if err := os.MkdirAll(*dir, 0o755); err != nil { // #nosec G301 -- migrations directory is project source, world-readable by design
		fmt.Fprintf(stderr, "wowapi migrate create: %v\n", err)
		return 1
	}
	path := filepath.Join(*dir, fmt.Sprintf("%05d_%s.sql", next, *name))
	if _, err := os.Stat(path); err == nil {
		fmt.Fprintf(stderr, "wowapi migrate create: %s already exists\n", path)
		return 1
	}
	body := "-- " + fmt.Sprintf("%05d_%s", next, *name) + ": TODO describe this migration.\n\n" +
		"-- +goose Up\n\n\n-- +goose Down\n\n"
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil { // #nosec G306 -- generated migration stub is project source, world-readable by design
		fmt.Fprintf(stderr, "wowapi migrate create: %v\n", err)
		return 1
	}
	fmt.Fprintln(stdout, path)
	return 0
}

// nextMigrationNumber returns max(existing NNNNN)+1, or 1 for an empty/absent dir.
func nextMigrationNumber(dir string) (int, error) {
	entries, err := os.ReadDir(dir)
	if os.IsNotExist(err) {
		return 1, nil
	}
	if err != nil {
		return 0, err
	}
	max := 0
	for _, e := range entries {
		m := migFileRE.FindStringSubmatch(e.Name())
		if m == nil {
			continue
		}
		n, _ := strconv.Atoi(m[1])
		if n > max {
			max = n
		}
	}
	return max + 1, nil
}
