package testkit

import (
	"context"
	"testing"
	"time"

	"github.com/google/uuid"

	"github.com/qatoolist/wowapi/kernel/workflow"
)

// This file closes coverage gap F-2: every tenant-scoped RLS table must have an
// isolation regression test, not just the handful with hand-written per-domain
// tests. Policies for these tables are generated by shared migration loops, so
// uniformity is high — but nothing else fails when a newly added table forgets
// FORCE ROW LEVEL SECURITY or ships an asymmetric USING/WITH CHECK. The table
// below drives testkit.AssertRLSIsolationSeeded (the real four-property probe)
// over the full census, and TestIntegrationRLSCensusComplete makes the list
// self-maintaining: adding a tenant-scoped RLS table without registering it here
// (or explicitly excluding it) fails the suite.

// rlsProbeTable names a tenant-scoped RLS table and builds one minimal probe row
// for it (EXCLUDING tenant_id, which AssertRLSIsolationSeeded supplies).
type rlsProbeTable struct {
	name string
	// platformWritten marks tables that only app_platform (not app_rt) may
	// write — authz config, audit anchors, integration/webhook config. Their
	// isolation is probed under app_platform, the role that operates them.
	platformWritten bool
	// row returns the non-tenant columns of one probe row. It may seed FK parents
	// via the Admin pool (which bypasses RLS, like a platform provisioner) and
	// return their ids. It is called once per insert, so id/unique columns must
	// differ between calls — hence uuid.New()/randHex() for them.
	row func(t *testing.T, h *DBHandle, tenant uuid.UUID) map[string]any
}

// rlsExcluded are tenant-scoped RLS tables deliberately NOT covered by the
// uniform strict-isolation probe — each for a structurally verifiable reason
// (assertExcludable enforces the reason, so a table cannot dodge the probe just
// by being listed here). Grouped by reason for documentation only.
var rlsExcluded = []string{
	// Hybrid catalog/config tables: either a RESTRICTIVE secondary policy
	// (owner/platform write) layered on tenant isolation, or a LOOSE tenant
	// policy — app_tenant_id_or_null() / "tenant_id IS NULL" shared rows, or a
	// permissive platform-write policy — rather than simple per-tenant isolation.
	"document_access_grants",
	"integration_providers",
	"notification_templates",
	"policies",
	"roles",
	"rule_versions",
	"audit_anchors",
	// Grant-only tables: app_rt has no direct per-tenant SELECT path; they are
	// driven by privileged job workers and covered by their own tests.
	"jobs_queue",
	"job_runs",
	"identity_grant",
}

// tenantScopedRLSProbeTables is the authoritative Group-A census: every simple
// per-tenant RLS table whose isolation is probed uniformly.
//
// ADD EVERY NEW TENANT-SCOPED RLS TABLE HERE (or, if it uses a RESTRICTIVE
// secondary policy, to rlsRestrictiveExcluded). TestIntegrationRLSCensusComplete
// cross-checks this list against the live catalog and fails if either drifts.
func tenantScopedRLSProbeTables() []rlsProbeTable {
	return []rlsProbeTable{
		{name: "acting_capacities", row: func(t *testing.T, h *DBHandle, tenant uuid.UUID) map[string]any {
			return map[string]any{"id": uuid.New(), "user_id": CreateUser(t, h), "label": "member", "created_by": uuid.Nil}
		}},
		{name: "actor_assignments", platformWritten: true, row: func(t *testing.T, h *DBHandle, tenant uuid.UUID) map[string]any {
			return map[string]any{
				"id": uuid.New(), "role_id": seedRole(t, h, tenant), "system_actor": "system:test",
				"scope_kind": "tenant", "granted_by": uuid.Nil, "created_by": uuid.Nil,
			}
		}},
		// NOTE: policies, roles, rule_versions and audit_anchors
		// are intentionally NOT probed here — they are hybrid catalog/config tables
		// (loose app_tenant_id_or_null / tenant_id IS NULL policies, or a permissive
		// platform-write policy) rather than simple per-tenant tables. They live in
		// rlsExcluded and are guarded structurally by assertExcludable.
		{name: "api_keys", row: func(t *testing.T, h *DBHandle, tenant uuid.UUID) map[string]any {
			return map[string]any{"id": uuid.New(), "name": "k-" + randHex(8), "key_prefix": randHex(8), "key_hash": randHex(16)}
		}},
		{name: "artifacts", row: func(t *testing.T, h *DBHandle, tenant uuid.UUID) map[string]any {
			return map[string]any{"id": uuid.New(), "kind": "k-" + randHex(8), "version": 1, "content_hash": randHex(16), "content": []byte("x")}
		}},
		{name: "attachments", row: func(t *testing.T, h *DBHandle, tenant uuid.UUID) map[string]any {
			return map[string]any{
				"id": uuid.New(), "resource_type": "document", "resource_id": uuid.New(),
				"document_version_id": seedDocumentVersion(t, h, tenant), "created_by": uuid.Nil,
			}
		}},
		{name: "audit_chain", row: func(t *testing.T, h *DBHandle, tenant uuid.UUID) map[string]any {
			// PK is tenant_id alone; next_seq/head_hash have defaults.
			return map[string]any{}
		}},
		{name: "authz_epoch", row: func(t *testing.T, h *DBHandle, tenant uuid.UUID) map[string]any {
			// PK is tenant_id alone; epoch has a default.
			return map[string]any{}
		}},
		{name: "audit_logs", row: func(t *testing.T, h *DBHandle, tenant uuid.UUID) map[string]any {
			return map[string]any{"id": uuid.New(), "action": "test.action", "seq": randInt63(), "row_hash": randHex(16)}
		}},
		{name: "bulk_items", row: func(t *testing.T, h *DBHandle, tenant uuid.UUID) map[string]any {
			return map[string]any{"id": uuid.New(), "bulk_id": seedBulkOperation(t, h, tenant), "seq": int(randInt63() & 0x7fffffff)}
		}},
		{name: "bulk_operations", row: func(t *testing.T, h *DBHandle, tenant uuid.UUID) map[string]any {
			return map[string]any{"id": uuid.New(), "kind": "k-" + randHex(8)}
		}},
		{name: "comments", row: func(t *testing.T, h *DBHandle, tenant uuid.UUID) map[string]any {
			return map[string]any{
				"id": uuid.New(), "resource_type": "document", "resource_id": uuid.New(),
				"author_capacity_id": uuid.New(), "body": "hello", "created_by": uuid.Nil,
			}
		}},
		{name: "document_versions", row: func(t *testing.T, h *DBHandle, tenant uuid.UUID) map[string]any {
			return map[string]any{
				"id": uuid.New(), "document_id": seedDocument(t, h, tenant), "version_no": 1,
				"storage_key": "s/" + randHex(8), "mime_type": "text/plain", "size_bytes": int64(1),
				"checksum_sha256": randHex(16), "uploaded_by": uuid.Nil,
			}
		}},
		{name: "document_upload_sessions", row: func(t *testing.T, h *DBHandle, tenant uuid.UUID) map[string]any {
			return map[string]any{
				"id": uuid.New(), "document_id": seedDocument(t, h, tenant), "version_no": 1,
				"storage_key": "s/" + randHex(8), "status": "pending",
				"expires_at": time.Now().Add(time.Hour),
			}
		}},
		{name: "documents", row: func(t *testing.T, h *DBHandle, tenant uuid.UUID) map[string]any {
			return map[string]any{"id": uuid.New(), "document_class": "generic", "title": "t", "created_by": uuid.Nil}
		}},
		{name: "dsr_requests", row: func(t *testing.T, h *DBHandle, tenant uuid.UUID) map[string]any {
			return map[string]any{"id": uuid.New(), "subject_ref": "party:" + randHex(8), "kind": "export"}
		}},
		{name: "events_outbox", row: func(t *testing.T, h *DBHandle, tenant uuid.UUID) map[string]any {
			return map[string]any{"id": uuid.New(), "event_type": "test.event", "created_by": uuid.Nil}
		}},
		{name: "idempotency_keys", row: func(t *testing.T, h *DBHandle, tenant uuid.UUID) map[string]any {
			return map[string]any{
				"actor_scope": "test", "idem_key": randHex(16), "request_hash": randHex(16),
				"expires_at": time.Now().Add(time.Hour),
			}
		}},
		{name: "legal_entities", row: func(t *testing.T, h *DBHandle, tenant uuid.UUID) map[string]any {
			return map[string]any{"party_id": seedParty(t, h, tenant), "legal_name": "Acme " + randHex(4)}
		}},
		{name: "legal_holds", row: func(t *testing.T, h *DBHandle, tenant uuid.UUID) map[string]any {
			return map[string]any{"id": uuid.New(), "entity_type": "document", "entity_id": uuid.New(), "reason": "litigation"}
		}},
		{name: "notification_channel_prefs", row: func(t *testing.T, h *DBHandle, tenant uuid.UUID) map[string]any {
			return map[string]any{"party_id": uuid.New(), "channel": "email"}
		}},
		{name: "notification_deliveries", row: func(t *testing.T, h *DBHandle, tenant uuid.UUID) map[string]any {
			return map[string]any{
				"id": uuid.New(), "notification_id": seedNotification(t, h, tenant),
				"channel": "email", "destination": "user@example.test",
			}
		}},
		{name: "notifications", row: func(t *testing.T, h *DBHandle, tenant uuid.UUID) map[string]any {
			return map[string]any{"id": uuid.New(), "template_key": "welcome", "recipient_party_id": uuid.New(), "created_by": uuid.Nil}
		}},
		{name: "organizations", row: func(t *testing.T, h *DBHandle, tenant uuid.UUID) map[string]any {
			return map[string]any{"id": uuid.New(), "name": "Org " + randHex(6), "created_by": uuid.Nil}
		}},
		{name: "parties", row: func(t *testing.T, h *DBHandle, tenant uuid.UUID) map[string]any {
			return map[string]any{"id": uuid.New(), "kind": "person", "display_name": "P " + randHex(4), "created_by": uuid.Nil}
		}},
		{name: "party_contacts", row: func(t *testing.T, h *DBHandle, tenant uuid.UUID) map[string]any {
			return map[string]any{
				"id": uuid.New(), "party_id": seedParty(t, h, tenant), "kind": "email",
				"value": randHex(8) + "@example.test", "created_by": uuid.Nil,
			}
		}},
		{name: "persons", row: func(t *testing.T, h *DBHandle, tenant uuid.UUID) map[string]any {
			return map[string]any{"party_id": seedParty(t, h, tenant), "given_name": "Given"}
		}},
		{name: "processed_events", row: func(t *testing.T, h *DBHandle, tenant uuid.UUID) map[string]any {
			return map[string]any{"handler": "test.handler", "event_id": uuid.New()}
		}},
		{name: "relationships", platformWritten: true, row: func(t *testing.T, h *DBHandle, tenant uuid.UUID) map[string]any {
			return map[string]any{
				"id": uuid.New(), "rel_type": seedRelationshipType(t, h), "subject_kind": "party", "subject_id": uuid.New(),
				"object_kind": "party", "object_id": uuid.New(), "created_by": uuid.Nil,
			}
		}},
		{name: "resources", row: func(t *testing.T, h *DBHandle, tenant uuid.UUID) map[string]any {
			return map[string]any{"id": uuid.New(), "resource_type": seedResourceType(t, h), "label": "r", "created_by": uuid.Nil}
		}},
		{name: "sequence_allocations", row: func(t *testing.T, h *DBHandle, tenant uuid.UUID) map[string]any {
			return map[string]any{"id": uuid.New(), "series_key": "seq-" + randHex(8), "value": int64(1)}
		}},
		{name: "sequences", row: func(t *testing.T, h *DBHandle, tenant uuid.UUID) map[string]any {
			return map[string]any{"series_key": "seq-" + randHex(8)}
		}},
		{name: "version_counters", row: func(t *testing.T, h *DBHandle, tenant uuid.UUID) map[string]any {
			return map[string]any{"scope": "test-" + randHex(8), "value": 1}
		}},
		{name: "webhook_failed_signature_audit", row: func(t *testing.T, h *DBHandle, tenant uuid.UUID) map[string]any {
			return map[string]any{
				"id": uuid.New(), "endpoint_id": seedWebhookEndpoint(t, h, tenant),
				"event_type": "test.event", "failure_reason": "invalid signature",
			}
		}},
		{name: "webhook_endpoints", platformWritten: true, row: func(t *testing.T, h *DBHandle, tenant uuid.UUID) map[string]any {
			return map[string]any{"id": uuid.New(), "direction": "inbound", "secret_ref": "ref-" + randHex(8), "created_by": uuid.Nil}
		}},
		{name: "webhook_events", row: func(t *testing.T, h *DBHandle, tenant uuid.UUID) map[string]any {
			return map[string]any{
				"id": uuid.New(), "endpoint_id": seedWebhookEndpoint(t, h, tenant), "direction": "inbound",
				"event_type": "test.event", "payload": []byte("{}"),
			}
		}},
		{name: "workflow_instances", row: func(t *testing.T, h *DBHandle, tenant uuid.UUID) map[string]any {
			return map[string]any{
				"id": uuid.New(), "definition_id": seedWorkflowDefinition(t, h, tenant), "resource_type": "document",
				"resource_id": uuid.New(), "current_step": "start", "started_by": uuid.Nil, "created_by": uuid.Nil,
			}
		}},
		{name: "workflow_task_assignees", row: func(t *testing.T, h *DBHandle, tenant uuid.UUID) map[string]any {
			return map[string]any{"task_id": seedWorkflowTask(t, h, tenant), "assignee_kind": "capacity", "assignee_ref": randHex(8)}
		}},
		{name: "workflow_tasks", row: func(t *testing.T, h *DBHandle, tenant uuid.UUID) map[string]any {
			return map[string]any{
				"id": uuid.New(), "instance_id": seedWorkflowInstance(t, h, tenant), "step_key": "review",
				"task_type": "approval", "created_by": uuid.Nil,
			}
		}},
	}
}

// TestIntegrationRLSIsolationAllTenantTables runs the full four-property RLS
// probe over every tenant-scoped RLS table in the census. It fails if any table
// loses FORCE RLS or its USING/WITH CHECK symmetry (a leaked cross-tenant read
// or an accepted cross-tenant write).
func TestIntegrationRLSIsolationAllTenantTables(t *testing.T) {
	h := NewDB(t)
	tables := tenantScopedRLSProbeTables()

	for _, tbl := range tables {
		t.Run(tbl.name, func(t *testing.T) {
			// FORCE RLS is invisible to a probe run as app_rt/app_platform (both are
			// non-owners, always subject to RLS). Assert it structurally so a table
			// that drops FORCE — letting its owner bypass isolation — is caught.
			assertForceRLS(t, h, tbl.name)

			tenantA := CreateTenant(t, h).ID
			tenantB := CreateTenant(t, h).ID
			writeTxM := h.TxM
			if tbl.platformWritten {
				writeTxM = h.PlatformTxM
			}
			factory := tbl.row
			AssertRLSIsolationSeeded(t, h, tbl.name, tenantA, tenantB,
				func(tenant uuid.UUID) map[string]any { return factory(t, h, tenant) }, writeTxM)
		})
	}
}

// TestIntegrationRLSCensusComplete makes the probe list self-maintaining: it
// compares the hard-coded census (probe list ∪ RESTRICTIVE-excluded) against the
// live set of tenant-scoped RLS tables and fails on any drift, so a newly added
// table cannot silently escape isolation testing.
//
// It also guards BOTH directions structurally via assertExcludable: every
// excluded table must genuinely be non-strict (RESTRICTIVE policy, a loose
// tenant policy, or no app_rt read path), and every PROBED table must genuinely
// be strict. So a table cannot dodge the probe by being listed as excluded, and
// a probed table that is later loosened (e.g. switched to app_tenant_id_or_null)
// fails here even if the behavioral probe still happens to pass.
func TestIntegrationRLSCensusComplete(t *testing.T) {
	h := NewDB(t)

	live := liveTenantScopedRLSTables(t, h)

	covered := map[string]bool{}
	for _, tbl := range tenantScopedRLSProbeTables() {
		if covered[tbl.name] {
			t.Errorf("duplicate table %q in tenantScopedRLSProbeTables", tbl.name)
		}
		covered[tbl.name] = true
	}
	excluded := map[string]bool{}
	for _, name := range rlsExcluded {
		if excluded[name] {
			t.Errorf("duplicate table %q in rlsExcluded", name)
		}
		excluded[name] = true
	}

	// Every live tenant-scoped RLS table must be either probed or explicitly excluded.
	for name := range live {
		if !covered[name] && !excluded[name] {
			t.Errorf("tenant-scoped RLS table %q is not covered: add it to tenantScopedRLSProbeTables "+
				"(or, if it is a hybrid/grant-only table, to rlsExcluded)", name)
		}
	}
	// Every registered/excluded table must still be a live tenant-scoped RLS table
	// (else it was renamed or lost RLS and the list is stale).
	for name := range covered {
		if !live[name] {
			t.Errorf("probed table %q is not a live tenant-scoped RLS table (renamed or lost RLS?)", name)
		}
	}
	for name := range excluded {
		if !live[name] {
			t.Errorf("excluded table %q is not a live tenant-scoped RLS table (renamed or lost RLS?)", name)
		}
	}

	// Anti-dodge, both directions: excluded tables must be non-strict; probed
	// tables must be strict.
	for name := range excluded {
		if live[name] && !isExcludable(t, h, name) {
			t.Errorf("table %q is in rlsExcluded but is a strict per-tenant table — it must be probed, not excluded", name)
		}
	}
	for name := range covered {
		if live[name] && isExcludable(t, h, name) {
			t.Errorf("table %q is probed as strict per-tenant but the catalog shows it is hybrid/loose/grant-only — "+
				"move it to rlsExcluded (or restore its strict tenant policy)", name)
		}
	}

	t.Logf("RLS census: %d live tenant-scoped tables = %d strict-probed + %d excluded",
		len(live), len(covered), len(excluded))
}

// isExcludable reports whether a tenant-scoped RLS table is NOT a simple,
// strictly-isolated per-tenant table, using only the live catalog. A table is
// excludable when any of the following holds:
//   - it carries a RESTRICTIVE policy (secondary owner/platform-write gate);
//   - it has a LOOSE tenant policy — one referencing app_tenant_id_or_null() or
//     "tenant_id IS NULL" (shared platform rows / fail-to-empty), which breaks
//     the strict fail-closed contract;
//   - app_rt cannot SELECT it (grant-only: no per-tenant read path); or
//   - app_rt cannot INSERT it yet it has a permissive USING/CHECK "true" policy,
//     i.e. its write role bypasses the WITH CHECK tenant gate (audit anchors).
func isExcludable(t *testing.T, h *DBHandle, table string) bool {
	t.Helper()
	var restrictive, nullish, truePerm, appRTSelect, appRTInsert bool
	err := h.Admin.QueryRow(context.Background(), `
		SELECT
		  EXISTS (SELECT 1 FROM pg_policies p WHERE p.schemaname='public' AND p.tablename=$1 AND p.permissive='RESTRICTIVE'),
		  EXISTS (SELECT 1 FROM pg_policies p WHERE p.schemaname='public' AND p.tablename=$1
		           AND (p.qual LIKE '%app_tenant_id_or_null%' OR p.with_check LIKE '%app_tenant_id_or_null%'
		             OR p.qual LIKE '%tenant_id IS NULL%' OR p.with_check LIKE '%tenant_id IS NULL%')),
		  EXISTS (SELECT 1 FROM pg_policies p WHERE p.schemaname='public' AND p.tablename=$1
		           AND p.permissive='PERMISSIVE' AND (p.qual='true' OR p.with_check='true')),
		  EXISTS (SELECT 1 FROM information_schema.role_table_grants g WHERE g.table_schema='public'
		           AND g.table_name=$1 AND g.grantee='app_rt' AND g.privilege_type='SELECT'),
		  EXISTS (SELECT 1 FROM information_schema.role_table_grants g WHERE g.table_schema='public'
		           AND g.table_name=$1 AND g.grantee='app_rt' AND g.privilege_type='INSERT')`,
		table).Scan(&restrictive, &nullish, &truePerm, &appRTSelect, &appRTInsert)
	if err != nil {
		t.Fatalf("classify %s: %v", table, err)
	}
	return restrictive || nullish || !appRTSelect || (!appRTInsert && truePerm)
}

// assertForceRLS fails unless the table has both ROW LEVEL SECURITY enabled and
// FORCED (so even the table owner is subject to the policies).
func assertForceRLS(t *testing.T, h *DBHandle, table string) {
	t.Helper()
	var enabled, forced bool
	if err := h.Admin.QueryRow(context.Background(),
		`SELECT c.relrowsecurity, c.relforcerowsecurity
		   FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
		  WHERE n.nspname = 'public' AND c.relname = $1`, table).Scan(&enabled, &forced); err != nil {
		t.Fatalf("query pg_class for %s: %v", table, err)
	}
	if !enabled {
		t.Errorf("table %q does not have ROW LEVEL SECURITY enabled", table)
	}
	if !forced {
		t.Errorf("table %q does not FORCE ROW LEVEL SECURITY (owner can bypass tenant isolation)", table)
	}
}

// liveTenantScopedRLSTables returns the authoritative live set: public tables
// with RLS enabled that carry a tenant_id column.
func liveTenantScopedRLSTables(t *testing.T, h *DBHandle) map[string]bool {
	t.Helper()
	rows, err := h.Admin.Query(context.Background(), `
		SELECT c.relname
		  FROM pg_class c
		  JOIN pg_namespace n ON n.oid = c.relnamespace
		 WHERE n.nspname = 'public' AND c.relrowsecurity
		   AND EXISTS (SELECT 1 FROM information_schema.columns col
		                WHERE col.table_schema = 'public' AND col.table_name = c.relname
		                  AND col.column_name = 'tenant_id')`)
	if err != nil {
		t.Fatalf("query live tenant-scoped RLS tables: %v", err)
	}
	defer rows.Close()

	set := map[string]bool{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			t.Fatalf("scan table name: %v", err)
		}
		set[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("iterate tenant-scoped RLS tables: %v", err)
	}
	return set
}

// --- FK-parent seed helpers (Admin pool bypasses RLS, like a provisioner) ---

func seedParty(t *testing.T, h *DBHandle, tenant uuid.UUID) uuid.UUID {
	t.Helper()
	id := uuid.New()
	execAdmin(t, h, `INSERT INTO parties (id, tenant_id, kind, display_name, created_by) VALUES ($1,$2,'person',$3,$4)`,
		id, tenant, "P "+randHex(4), uuid.Nil)
	return id
}

func seedDocument(t *testing.T, h *DBHandle, tenant uuid.UUID) uuid.UUID {
	t.Helper()
	id := uuid.New()
	execAdmin(t, h, `INSERT INTO documents (id, tenant_id, document_class, title, created_by) VALUES ($1,$2,'generic',$3,$4)`,
		id, tenant, "t", uuid.Nil)
	return id
}

func seedDocumentVersion(t *testing.T, h *DBHandle, tenant uuid.UUID) uuid.UUID {
	t.Helper()
	id := uuid.New()
	execAdmin(t, h, `INSERT INTO document_versions
		(id, tenant_id, document_id, version_no, storage_key, mime_type, size_bytes, checksum_sha256, uploaded_by)
		VALUES ($1,$2,$3,1,$4,'text/plain',1,$5,$6)`,
		id, tenant, seedDocument(t, h, tenant), "s/"+randHex(8), randHex(16), uuid.Nil)
	return id
}

func seedBulkOperation(t *testing.T, h *DBHandle, tenant uuid.UUID) uuid.UUID {
	t.Helper()
	id := uuid.New()
	execAdmin(t, h, `INSERT INTO bulk_operations (id, tenant_id, kind) VALUES ($1,$2,$3)`, id, tenant, "k-"+randHex(8))
	return id
}

func seedNotification(t *testing.T, h *DBHandle, tenant uuid.UUID) uuid.UUID {
	t.Helper()
	id := uuid.New()
	execAdmin(t, h, `INSERT INTO notifications (id, tenant_id, template_key, recipient_party_id, created_by) VALUES ($1,$2,'welcome',$3,$4)`,
		id, tenant, uuid.New(), uuid.Nil)
	return id
}

func seedWebhookEndpoint(t *testing.T, h *DBHandle, tenant uuid.UUID) uuid.UUID {
	t.Helper()
	id := uuid.New()
	execAdmin(t, h, `INSERT INTO webhook_endpoints (id, tenant_id, direction, secret_ref, created_by) VALUES ($1,$2,'inbound',$3,$4)`,
		id, tenant, "ref-"+randHex(8), uuid.Nil)
	return id
}

func seedRole(t *testing.T, h *DBHandle, tenant uuid.UUID) uuid.UUID {
	t.Helper()
	id := uuid.New()
	execAdmin(t, h, `INSERT INTO roles (id, tenant_id, key, name, created_by) VALUES ($1,$2,$3,$4,$5)`,
		id, tenant, "role-"+randHex(8), "Role", uuid.Nil)
	return id
}

func seedWorkflowDefinition(t *testing.T, h *DBHandle, tenant uuid.UUID) uuid.UUID {
	t.Helper()
	key := "wf-" + randHex(8)
	reg := workflow.NewRegistry()
	if err := reg.RegisterDefinition(workflow.Definition{
		Key: key, Version: 1, AppliesTo: "document", InitialStep: "done",
		Steps: map[string]workflow.Step{"done": {Type: workflow.StepTerminal, Outcome: "completed"}},
	}); err != nil {
		t.Fatal(err)
	}
	if err := reg.Err(); err != nil {
		t.Fatal(err)
	}
	if err := workflow.SyncDefinitions(context.Background(), h.Platform, reg); err != nil {
		t.Fatal(err)
	}
	var id uuid.UUID
	if err := h.Admin.QueryRow(context.Background(),
		`SELECT id FROM workflow_definitions WHERE key = $1 AND version = 1`, key).Scan(&id); err != nil {
		t.Fatal(err)
	}
	return id
}

func seedWorkflowInstance(t *testing.T, h *DBHandle, tenant uuid.UUID) uuid.UUID {
	t.Helper()
	id := uuid.New()
	execAdmin(t, h, `INSERT INTO workflow_instances
		(id, tenant_id, definition_id, resource_type, resource_id, current_step, started_by, created_by)
		VALUES ($1,$2,$3,'document',$4,'start',$5,$6)`,
		id, tenant, seedWorkflowDefinition(t, h, tenant), uuid.New(), uuid.Nil, uuid.Nil)
	return id
}

func seedWorkflowTask(t *testing.T, h *DBHandle, tenant uuid.UUID) uuid.UUID {
	t.Helper()
	id := uuid.New()
	execAdmin(t, h, `INSERT INTO workflow_tasks (id, tenant_id, instance_id, step_key, task_type, created_by)
		VALUES ($1,$2,$3,'review','approval',$4)`, id, tenant, seedWorkflowInstance(t, h, tenant), uuid.Nil)
	return id
}

func seedResourceType(t *testing.T, h *DBHandle) string {
	t.Helper()
	key := "rt_" + randHex(8)
	CreateResourceType(t, h, key)
	return key
}

func seedRelationshipType(t *testing.T, h *DBHandle) string {
	t.Helper()
	key := "rel_" + randHex(8)
	execAdmin(t, h, `INSERT INTO relationship_types (key, module, subject_kind, object_kind, description)
		VALUES ($1,'test','party','party',$2)`, key, key)
	return key
}

// randInt63 returns a non-negative pseudo-unique 62-bit int for columns that
// only need to differ between the two probe inserts (e.g. audit sequences).
func randInt63() int64 {
	b := randHex(15) // 60 bits
	var v int64
	for _, c := range b {
		v <<= 4
		switch {
		case c >= '0' && c <= '9':
			v |= int64(c - '0')
		default:
			v |= int64(c-'a') + 10
		}
	}
	if v < 0 {
		v = -v
	}
	return v
}
